### PR TITLE
chore: add build types and update all the dependencies

### PR DESCRIPTION
**Pull request by selemondev**

### CODE REVIEW

**Review by Boluwatife2904 — APPROVED** [review]
@selemondev this would add type definitions/auto-completion when using the component right 🤔? You cannot imagine the stress I have gone through to do this 😭

**Comment by selemondev** [comment]
Yes ✨

**Comment by Boluwatife2904** [comment]
> Yes ✨

Sweettttttt 🤩. Well done Man 🙌🏽🙌🏽

**Comment by Boluwatife2904** [comment]
Hey Chief @selemondev , I just tested after merging and it didn't work. What do You think the issue might be 🤔

Screenshot 2023-04-24 at 12 56 28

**Comment by Boluwatife2904** [comment]
Also, I just created a new development branch so we can use that for testing before deploying to main.

**Comment by Boluwatife2904** [comment]
The reason I had the first error was because I had a shim.vue.ts file in the project I was using to test so I removed that and now, I'm not getting any auto completion.

Screenshot 2023-04-24 at 13 02 23

**Pull request merged**
